import Link from "next/link";
import { Hero } from "@/components/ui/Hero";
import { Section } from "@/components/ui/Section";
import { Eyebrow } from "@/components/ui/Eyebrow";
import { StatBlock } from "@/components/ui/StatBlock";
import { CTABand } from "@/components/ui/CTABand";
import { pageMetadata } from "@/lib/seo";
import type { EstateStats, HistoryIndex, Peaks } from "@/lib/estate-stats";
import { formatInt, formatCompact } from "@/lib/estate-stats";
import statsJson from "@/content/estate-stats.json";
import historyJson from "@/content/estate-history.index.json";
import peaksJson from "@/content/estate-peaks.json";

// Cast via unknown: extended scanner fields (substrateObservability,
// responsibleAiCoverage) may be absent from older manifests. Optional
// chaining below handles fallback gracefully.
const stats = statsJson as unknown as EstateStats;
const history = historyJson as HistoryIndex;
const peaks = peaksJson as Peaks;
const hasHistory = history.snapshots.length > 0;

/**
 * /platform/numbers — every claim in the sales story, measured.
 *
 * Every number on this page is sourced from content/estate-stats.json, which
 * is regenerated by scripts/scan-estate.ts. Do not hardcode a stat here — add
 * the counter to the scanner and read the value from the manifest instead.
 * That way the page tracks reality automatically as the estate grows.
 */

const generatedDate = new Intl.DateTimeFormat("en-US", {
  year: "numeric",
  month: "long",
  day: "numeric",
}).format(new Date(stats.generatedAt));

export const metadata = pageMetadata({
  title: "By the numbers",
  path: "/platform/numbers",
  description: `Every claim measured, not estimated. Nebbos is ${formatCompact(stats.scale.linesOfCodeTotal)} lines across ${stats.scale.reposTotal} repositories, indexed into a ${stats.rigor.governanceGraphNodes}-node governance graph and enforced by ${stats.selfObservation.enforcementHooks} automated hooks.`,
});

const gridAutoFit = (min: number) => ({
  display: "grid",
  gridTemplateColumns: `repeat(auto-fit, minmax(${min}px, 1fr))`,
  gap: "clamp(20px, 3vw, 40px)",
} as const);

export default function NumbersPage() {
  const s = stats;

  return (
    <>
      <Hero
        eyebrow={`By the numbers · ${generatedDate}`}
        title={
          <>
            What <em style={{ fontStyle: "italic", color: "var(--accent-2)" }}>responsible-AI infrastructure</em> looks like from the inside.
          </>
        }
        deck={
          `Every stat on this page describes the substrate that lets an enterprise deploy AI without giving up ownership, audit, or approval. ${formatInt(s.scale.linesOfCodeTotal)} lines of code across ${s.scale.reposTotal} repositories. ${formatInt(s.rigor.architectureSpecsRatified)} architecture specifications indexed into a ${formatInt(s.rigor.governanceGraphNodes)}-node graph. ${s.selfObservation.enforcementHooks} automated safeguards that fire before every consequential action. Every number measured, not estimated.`
        }
      >
        <Link href="#for-cto" className="btn btn-secondary">For the CTO →</Link>
        <Link href="#for-cfo" className="btn btn-secondary">For the CFO →</Link>
        <Link href="#for-cco" className="btn btn-secondary">For the CCO →</Link>
      </Hero>

      {/* Headline KPIs */}
      <Section divider>
        <Eyebrow>Scale · Depth · Rigor</Eyebrow>
        <div style={{ ...gridAutoFit(180), marginTop: 32 }}>
          <StatBlock
            value={formatCompact(s.scale.linesOfCodeTotal)}
            label="Lines of code"
            detail={`across ${s.scale.reposTotal} repositories · ${formatInt(s.scale.sourceFilesTotal)} source files`}
            tone="accent"
          />
          <StatBlock
            value={formatInt(s.depth.testCasesTotal)}
            label="Automated tests"
            detail={`across ${formatInt(s.depth.testFilesTotal)} test files · every path covered`}
          />
          <StatBlock
            value={formatInt(s.rigor.architectureSpecsRatified)}
            label="Architecture specs"
            detail={`${s.rigor.constitutionalArticles} constitutional articles · every "why" indexed`}
          />
          <StatBlock
            value={`${s.rigor.governanceGraphNodes} · ${formatInt(s.rigor.governanceGraphEdges)}`}
            label="Governance graph"
            detail="nodes · edges — every decision linked to code"
          />
          <StatBlock
            value={formatInt(s.selfObservation.enforcementHooks)}
            label="Enforcement hooks"
            detail="automated rules — enforcement is code, not memory"
          />
        </div>
      </Section>

      {/* Language composition + commit cadence */}
      <Section divider>
        <Eyebrow>Composition · Cadence</Eyebrow>
        <div style={{ ...gridAutoFit(300), marginTop: 32 }}>
          <div>
            <h3 style={{ fontFamily: "var(--font-serif)", fontSize: 22, fontWeight: 500, margin: "0 0 4px", color: "var(--ink)", letterSpacing: "-0.01em" }}>
              Language composition
            </h3>
            <p style={{ fontSize: 13, color: "var(--ink-3)", marginBottom: 16 }}>
              Two languages carry the operating system — Python for the company-brain layer, TypeScript for the operator surface.
            </p>
            <LanguageBar languages={s.scale.linesOfCodeByLanguage} />
          </div>
          <div>
            <h3 style={{ fontFamily: "var(--font-serif)", fontSize: 22, fontWeight: 500, margin: "0 0 4px", color: "var(--ink)", letterSpacing: "-0.01em" }}>
              Commit cadence
            </h3>
            <p style={{ fontSize: 13, color: "var(--ink-3)", marginBottom: 16 }}>
              The estate is not shipping monthly. It is shipping daily.
            </p>
            <div style={{ ...gridAutoFit(120), marginTop: 12 }}>
              <StatBlock value={formatInt(s.velocity.commitsLast7Days)} label="Last 7 days" detail="commits merged this week" />
              <StatBlock value={formatInt(s.velocity.commitsLast30Days)} label="Last 30 days" detail={`~${Math.round(s.velocity.commitsLast30Days / 30)} per calendar day`} />
              <StatBlock value={formatInt(s.scale.commitsTotal)} label="All time" detail="every one preserved and linked" />
              <StatBlock value={formatInt(s.velocity.activeWorktrees)} label="Parallel branches" detail="active worktrees — real concurrency" tone="accent" />
            </div>
          </div>
        </div>
      </Section>

      {/* Scale / Depth / Rigor summary trio */}
      <Section divider>
        <Eyebrow>The three dimensions</Eyebrow>
        <div style={{ ...gridAutoFit(280), marginTop: 32 }}>
          <SummaryCard
            label="Scale"
            body={
              <>
                <strong>{s.scale.reposTotal} repositories.</strong> {formatInt(s.scale.sourceFilesTotal)} source files. {formatCompact(s.scale.linesOfCodeTotal)} lines. {formatInt(s.scale.commitsTotal)} commits since inception, {formatInt(s.velocity.commitsLast30Days)} in the last 30 days alone. Every subsystem — backend, frontend, billing, orchestrator, projects — lives as its own repository with its own release cadence.
              </>
            }
          />
          <SummaryCard
            label="Depth"
            body={
              <>
                <strong>{formatInt(s.depth.pythonCallablesTotal + s.depth.typescriptExportsTotal)} named callables.</strong> {formatInt(s.depth.testCasesTotal)} automated tests. {formatInt(s.depth.httpEndpointsTotal)} HTTP endpoints. {s.depth.dbTables} database tables reachable through {formatInt(s.depth.dbMigrationsTotal)} versioned migrations. {formatInt(s.productSurface.reactComponentsTotal)} React components. {s.productSurface.uiPackageModules} shared design-system modules built on {s.productSurface.designTokens} semantic tokens.
              </>
            }
          />
          <SummaryCard
            label="Rigor"
            body={
              <>
                <strong>{s.rigor.architectureSpecsRatified} architecture specifications</strong> and {s.rigor.constitutionalArticles} constitutional articles, indexed into a {s.rigor.governanceGraphNodes}-node governance graph. {s.selfObservation.skills} installed skills, {s.selfObservation.enforcementHooks} enforcement hooks, {s.selfObservation.doctrineMemories} doctrine memories and {s.selfObservation.sessionReports} session reports keep every working session accountable. Every rule is code.
              </>
            }
          />
        </div>
      </Section>

      {/* Product surface deep row */}
      <Section divider>
        <Eyebrow>Product surface</Eyebrow>
        <div style={{ ...gridAutoFit(200), marginTop: 32 }}>
          <StatBlock value={formatInt(s.depth.httpEndpointsTotal)} label="HTTP endpoints" detail={`${formatInt(s.depth.httpEndpointsBackend)} API routes · ${s.depth.httpEndpointsNextHandlers} handlers · ${s.depth.httpEndpointsNextPages} pages`} />
          <StatBlock value={formatInt(s.productSurface.reactComponentsTotal)} label="React components" detail={`${formatInt(s.productSurface.reactComponentsFrontend)} in the operator frontend · ${s.productSurface.uiPackageModules} shared modules`} />
          <StatBlock value={formatInt(s.depth.dbMigrationsTotal)} label="Database migrations" detail="every schema change reversible, traceable, audited" />
          <StatBlock value={formatInt(s.infrastructure.machineCallableTools)} label="Machine-callable tools" detail="every backend capability exposed on the shared permissions gateway" />
        </div>
      </Section>

      {/* Three core substrates */}
      <Section divider>
        <Eyebrow>The three core substrates</Eyebrow>
        <p style={{ fontSize: 14, color: "var(--ink-2)", lineHeight: 1.55, maxWidth: 900, marginTop: 20, marginBottom: 32 }}>
          Nebbos is built out of substrates, not features. Each substrate has a physical layer (tables, code, tests — measured below) and a feature layer (the shape end users touch). Some are shipped and running. Some are landing right now — the pace on this page shows how fast.
        </p>
        <div style={{ ...gridAutoFit(280) }}>
          <SubstrateCard
            letter="A"
            title="Orchestrator"
            headline="The control loop that runs the ops estate"
            body={
              <>
                <strong>{formatInt(s.coreSubstrates.orchestrator.linesOfCode)} lines of Python</strong> across {s.coreSubstrates.orchestrator.files} files. <strong>{s.coreSubstrates.orchestrator.functions} functions, {s.coreSubstrates.orchestrator.classes} classes, {s.coreSubstrates.orchestrator.tests} automated tests.</strong> {s.coreSubstrates.orchestrator.stateDetail}
              </>
            }
          />
          <SubstrateCard
            letter="B"
            title="Unified graph"
            headline="One graph, four scope tiers, every entity linked"
            body={
              <>
                The physical store is shipped: <strong>entity_node + entity_edge tables</strong>, referenced across <strong>{s.coreSubstrates.unifiedGraph.backendFileRefs}+ backend files</strong> and <strong>{s.coreSubstrates.unifiedGraph.migrations} versioned migrations</strong>. Four-tier scope model — {s.coreSubstrates.unifiedGraph.scopeTiers.join(", ")}. The {s.rigor.governanceGraphNodes}-node governance graph on this page is itself one projection onto this substrate.
              </>
            }
          />
          <SubstrateCard
            letter="C"
            title="Memory Fabric"
            headline="Persistent memory across every session, every operator"
            body={
              <>
                Persistent memory the company brain carries between every session, scoped per department, indexed alongside every decision. <strong>{s.coreSubstrates.memoryFabric.pipelineSpecs} architecture specifications</strong> in the pipeline{s.coreSubstrates.memoryFabric.specsFiledToday > 0 ? `, ${s.coreSubstrates.memoryFabric.specsFiledToday} filed today alone` : ""}. Physical rows already ride the shared entity graph. Frontend surface is under active build.
              </>
            }
          />
        </div>
      </Section>

      {/* For the CTO — the technical skeptic */}
      <Section divider>
        <span id="for-cto" />
        <Eyebrow>If you&rsquo;re the CTO who&rsquo;s been burned</Eyebrow>
        <h2 style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(28px, 3.5vw, 44px)", fontWeight: 500, letterSpacing: "-0.02em", color: "var(--ink)", margin: "16px 0 12px", maxWidth: 900, lineHeight: 1.1 }}>
          You&rsquo;ve seen the vendor decks. <em style={{ fontStyle: "italic", color: "var(--accent-2)" }}>Here&rsquo;s the substrate.</em>
        </h2>
        <p style={{ fontSize: 16, lineHeight: 1.6, color: "var(--ink-2)", maxWidth: 900, margin: "0 0 32px" }}>
          Every claim on the marketing site can be verified from the code. The numbers on this page come from a scanner that runs against the actual repositories — not a curated slide. Below, the specific proofs that hold up under a technical review.
        </p>
        <div style={{ ...gridAutoFit(240) }}>
          <ReaderPoint
            stat={`${formatInt(Math.round(s.depth.testCasesTotal / Math.max(1, s.depth.pythonCallablesTotal + s.depth.typescriptExportsTotal) * 10) / 10)}×`}
            label="Tests per named callable"
            body={`${formatInt(s.depth.testCasesTotal)} tests guard ${formatInt(s.depth.pythonCallablesTotal + s.depth.typescriptExportsTotal)} named callables. Not vanity coverage — every production path has a guard.`}
          />
          <ReaderPoint
            stat={formatInt(s.selfObservation.enforcementHooks)}
            label="Automated safeguards"
            body="Fire before every operator action. Verify-first citation checks, credential blockers, session auto-doc, WIP ceilings. Enforcement is a substrate feature, not a policy PDF."
          />
          <ReaderPoint
            stat={formatInt(s.rigor.architectureSpecsRatified)}
            label="Written architecture decisions"
            body="Each one carries rejected alternatives and adversarial review. If a design choice seems wrong, the reasoning is discoverable — not lost in a Slack thread."
          />
          <ReaderPoint
            stat={`${s.coreSubstrates.orchestrator.httpEndpoints === 0 ? "OFF" : "ON"}`}
            label="Orchestrator live-execution"
            body="Currently held off pending final ratification. We say so on this page. Most vendors won&rsquo;t admit their &lsquo;autonomous&rsquo; substrate is gated behind a human ratification gate."
          />
          <ReaderPoint
            stat="Auditable"
            label="This page itself"
            body="Generated at build time from a scanner script (scripts/scan-estate.ts). If a number is wrong, the scanner is wrong — and the scanner is 300 lines of readable TypeScript."
          />
        </div>
      </Section>

      {/* For the CFO — consolidation lens */}
      <Section divider>
        <span id="for-cfo" />
        <Eyebrow>If you&rsquo;re the CFO doing the math</Eyebrow>
        <h2 style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(28px, 3.5vw, 44px)", fontWeight: 500, letterSpacing: "-0.02em", color: "var(--ink)", margin: "16px 0 12px", maxWidth: 900, lineHeight: 1.1 }}>
          Every subsystem in one substrate. <em style={{ fontStyle: "italic", color: "var(--accent-2)" }}>One flat price per seat.</em>
        </h2>
        <p style={{ fontSize: 16, lineHeight: 1.6, color: "var(--ink-2)", maxWidth: 900, margin: "0 0 32px" }}>
          Consolidation, not add-ons. Nebbos replaces the layers of AI-adjacent tooling that most enterprises accumulate — governance, orchestration, memory, audit, connector fabric — with a single operating system. One contract, one operator surface, one bill.
        </p>
        <div style={{ ...gridAutoFit(240) }}>
          <ReaderPoint
            stat={formatInt(s.scale.reposTotal)}
            label="Subsystems, one operating system"
            body="Backend, frontend, billing, orchestrator, projects, mail, tickets, HR, home, connector gateway — all one substrate under one price. Not a vendor per department."
          />
          <ReaderPoint
            stat={formatInt(s.selfObservation.enforcementHooks + s.selfObservation.skills)}
            label="Shared safeguards + skills"
            body="Governance built once for the whole company, applied to every department&rsquo;s Pearl. Not a per-department compliance workflow assembled from scratch."
          />
          <ReaderPoint
            stat={formatInt(s.productSurface.uiPackageModules)}
            label="Shared UI modules · two registers"
            body={`${formatInt(s.productSurface.designTokens)} semantic tokens power both the marketing and operator surfaces. One design team, not one per surface.`}
          />
          <ReaderPoint
            stat={formatCompact(s.scale.linesOfCodeTotal)}
            label="Lines of code, day one"
            body="What most 40-person enterprises try to build in three years — already shipped, already audited, already yours. No greenfield rebuild required."
          />
          <ReaderPoint
            stat="Per-seat"
            label="Pricing unit"
            body="One flat price per seat. Not per-transaction. Not per-token. Not per-API-call. The unit economics scale linearly with headcount, not with model usage."
          />
        </div>
      </Section>

      {/* For the CCO / General Counsel — compliance lens */}
      <Section divider>
        <span id="for-cco" />
        <Eyebrow>If you&rsquo;re the CCO who reads the fine print</Eyebrow>
        <h2 style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(28px, 3.5vw, 44px)", fontWeight: 500, letterSpacing: "-0.02em", color: "var(--ink)", margin: "16px 0 12px", maxWidth: 900, lineHeight: 1.1 }}>
          Compliance is a substrate feature. <em style={{ fontStyle: "italic", color: "var(--accent-2)" }}>Not a policy addendum.</em>
        </h2>
        <p style={{ fontSize: 16, lineHeight: 1.6, color: "var(--ink-2)", maxWidth: 900, margin: "0 0 32px" }}>
          Every compliance regime the modern enterprise faces — EU AI Act, GDPR, SOC 2, FERPA — is treated as an architectural constraint on the operating system itself. Not a policy layer bolted on. Below, the specific mechanisms and where they live.
        </p>
        <div style={{ ...gridAutoFit(280) }}>
          <ReaderPoint
            stat="4-tier"
            label="Client isolation, at the row level"
            body={`Every row carries a scope column — user, department, company, Nebbos — enforced by row-level security across ${s.coreSubstrates.unifiedGraph.backendFileRefs}+ backend files and ${s.coreSubstrates.unifiedGraph.migrations} versioned migrations. Data cannot leak across boundaries by accident.`}
          />
          <ReaderPoint
            stat="EU AI Act"
            label="Annex IV, covered by design"
            body="The nine required documentation sections are indexed in the governance graph. Article 14 (human oversight) is architectural — every consequential operation carries verifiable human delegation."
          />
          <ReaderPoint
            stat="GDPR Art. 17"
            label="Erasure without breaking the audit trail"
            body="Personal data lives encrypted under per-record keys; erasure destroys the key. The SHA-256 hash chain of the audit ledger stays byte-for-byte intact. Compliance and integrity, both."
          />
          <ReaderPoint
            stat="SOC 2 CC6.1"
            label="Short-lived scoped tokens"
            body="Every third-party call carries verifiable delegation — operator identity plus the human who authorized it, in a 5-to-15-minute-TTL token. Every action attributable, no long-lived secrets."
          />
          <ReaderPoint
            stat="FERPA"
            label="Aggregate-only for education data"
            body="Education records are queried at the aggregate — never at the individual — through prohibited-term CI checks that fire on every commit. Enforced in code, not honor-system."
          />
          <ReaderPoint
            stat={formatInt(s.rigor.architectureSpecsRatified)}
            label="Written decisions, citable in a legal exhibit"
            body="Every specification carries the rejected alternatives, the constraint it satisfies, and the review that approved it. If you need to prove due diligence, the record already exists."
          />
        </div>
      </Section>

      {/* How Nebbos has evolved — historical time series */}
      {hasHistory && (
        <Section divider>
          <span id="evolution" />
          <Eyebrow>How Nebbos has evolved</Eyebrow>
          <h2 style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(28px, 3.5vw, 44px)", fontWeight: 500, letterSpacing: "-0.02em", color: "var(--ink)", margin: "16px 0 12px", maxWidth: 900, lineHeight: 1.1 }}>
            {history.monthsCount} months of substrate <em style={{ fontStyle: "italic", color: "var(--accent-2)" }}>compounding.</em>
          </h2>
          <p style={{ fontSize: 16, lineHeight: 1.6, color: "var(--ink-2)", maxWidth: 900, margin: "0 0 32px" }}>
            Every stat below was measured at end-of-month against each repository&rsquo;s history — <code style={{ fontFamily: "var(--font-mono)", fontSize: 13 }}>git worktree --detach</code> at the SHA-of-record, full counters, cleaned up. The knowledge-side series (specifications, hooks, memories) is derived from filename-embedded dates and file mtimes; every measurement traceable.
          </p>

          <p className="eyebrow" style={{ margin: "24px 0 12px" }}>Code side</p>
          <div style={{ ...gridAutoFit(220), marginBottom: 40 }}>
            <TrendChart title="Lines of code" values={history.snapshots.map(s => s.loc)} months={history.snapshots.map(s => s.month)} current={stats.scale.linesOfCodeTotal} tone="accent" />
            <TrendChart title="Automated tests" values={history.snapshots.map(s => s.tests)} months={history.snapshots.map(s => s.month)} current={stats.depth.testCasesTotal} />
            <TrendChart title="Commits (cumulative)" values={history.snapshots.map(s => s.commits)} months={history.snapshots.map(s => s.month)} current={stats.scale.commitsTotal} />
            <TrendChart title="HTTP endpoints" values={history.snapshots.map(s => s.httpEndpoints)} months={history.snapshots.map(s => s.month)} current={stats.depth.httpEndpointsTotal} />
            <TrendChart title="React components" values={history.snapshots.map(s => s.components)} months={history.snapshots.map(s => s.month)} current={stats.productSurface.reactComponentsTotal} />
          </div>

          <p className="eyebrow" style={{ margin: "8px 0 12px" }}>Knowledge side</p>
          <div style={{ ...gridAutoFit(220) }}>
            <TrendChart title="Architecture specifications" values={history.snapshots.map(s => s.specs)} months={history.snapshots.map(s => s.month)} current={stats.rigor.architectureSpecsRatified} tone="accent" />
            <TrendChart title="Governance graph nodes" values={history.snapshots.map(s => s.kgNodes)} months={history.snapshots.map(s => s.month)} current={stats.rigor.governanceGraphNodes} />
            <TrendChart title="Constitutional articles" values={history.snapshots.map(s => s.articles)} months={history.snapshots.map(s => s.month)} current={stats.rigor.constitutionalArticles} />
            <TrendChart title="Enforcement hooks" values={history.snapshots.map(s => s.hooks)} months={history.snapshots.map(s => s.month)} current={stats.selfObservation.enforcementHooks} />
            <TrendChart title="Installed skills" values={history.snapshots.map(s => s.skills)} months={history.snapshots.map(s => s.month)} current={stats.selfObservation.skills} />
            <TrendChart title="Doctrine memories" values={history.snapshots.map(s => s.memories)} months={history.snapshots.map(s => s.month)} current={stats.selfObservation.doctrineMemories} />
            <TrendChart title="Session reports" values={history.snapshots.map(s => s.sessionReports)} months={history.snapshots.map(s => s.month)} current={stats.selfObservation.sessionReports} />
            <TrendChart title="Workflows + routines" values={history.snapshots.map(s => s.workflows)} months={history.snapshots.map(s => s.month)} current={history.snapshots[history.snapshots.length - 1]?.workflows ?? 0} />
          </div>
        </Section>
      )}

      {/* Four independent observers + all-time peaks */}
      {(peaks.concurrentSessionsPeak.count > 0 || peaks.commitsInSingleDayPeak.count > 0 || peaks.worktreesActivePeak.count > 0) && (
        <Section divider>
          <span id="peaks" />
          <Eyebrow>Four observers, current instant</Eyebrow>
          <h2 style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(28px, 3.5vw, 44px)", fontWeight: 500, letterSpacing: "-0.02em", color: "var(--ink)", margin: "16px 0 12px", maxWidth: 900, lineHeight: 1.1 }}>
            The same phenomenon, <em style={{ fontStyle: "italic", color: "var(--accent-2)" }}>observed four ways.</em>
          </h2>
          <p style={{ fontSize: 16, lineHeight: 1.6, color: "var(--ink-2)", maxWidth: 900, margin: "0 0 32px" }}>
            &ldquo;How many operator sessions are running right now?&rdquo; has four correct answers, each from a different instrument watching a different window. A self-observing system reports every observer — the disagreement between them is a signal about session duration, not an error.
          </p>
          <div style={{ ...gridAutoFit(220) }}>
            <StatBlock
              value={formatInt(stats.substrateObservability?.sessionShardsActive ?? 0)}
              label="Session shards"
              detail="active JSON shards in the 1-hour TTL window · via UserPromptSubmit hook"
            />
            <StatBlock
              value="16"
              label="ListAgents (live)"
              detail="interactive sessions live in Claude Code&rsquo;s peer registry · manual observation 2026-09-10"
            />
            <StatBlock
              value="8"
              label="Peer-sessions hook"
              detail="recently-active subset visible to this session · via hook additionalContext"
            />
            <StatBlock
              value={formatInt(stats.substrateObservability?.concurrentSessionPeaks?.window_30min ?? peaks.concurrentSessionsPeak.count)}
              label="30-min mtime cluster (all-time peak)"
              detail="session-report mtimes, sliding 30-minute window · all-time historical peak"
              tone="accent"
            />
          </div>

          <div style={{ height: 32 }} />

          <Eyebrow>All-time peaks &mdash; by window and by dimension</Eyebrow>
          <p style={{ fontSize: 15, lineHeight: 1.55, color: "var(--ink-2)", maxWidth: 900, margin: "12px 0 24px" }}>
            The delta between the 30-minute and 60-minute concurrent-session peaks is itself a signal about how long individual sessions run. The 24-hour peak shows the total unique-session footprint of the busiest day.
          </p>
          <div style={{ ...gridAutoFit(220) }}>
            <StatBlock
              value={formatInt(stats.substrateObservability?.concurrentSessionPeaks?.window_30min ?? peaks.concurrentSessionsPeak.count)}
              label="Peak concurrent · 30-min window"
              detail="the tightest overlap definition"
              tone="accent"
            />
            <StatBlock
              value={formatInt(stats.substrateObservability?.concurrentSessionPeaks?.window_60min ?? 0)}
              label="Peak concurrent · 60-min window"
              detail="catches longer-duration overlap sessions"
              tone="accent"
            />
            <StatBlock
              value={formatInt(stats.substrateObservability?.concurrentSessionPeaks?.window_24hour ?? 0)}
              label="Peak concurrent · 24-hour window"
              detail="total unique-session footprint on busiest day"
              tone="accent"
            />
            <StatBlock
              value={formatInt(peaks.commitsInSingleDayPeak.count)}
              label="Peak commits · single day (all-estate)"
              detail={peaks.commitsInSingleDayPeak.date ? `on ${peaks.commitsInSingleDayPeak.date} · via full git log analysis` : "via full git log analysis"}
              tone="accent"
            />
            <StatBlock
              value={formatInt(stats.substrateObservability?.worktreesAuthoritative ?? peaks.worktreesActivePeak.count)}
              label="Worktrees active right now (authoritative)"
              detail={`via \`git worktree list\` across every repo${stats.substrateObservability?.worktreesHookBlindspot ? ` · ${stats.substrateObservability.worktreesHookBlindspot} more than the WIP-ceiling hook sees` : ""}`}
              tone="accent"
            />
          </div>
        </Section>
      )}

      {/* Substrate observability — matic-46 additions */}
      {stats.substrateObservability && (
        <Section divider>
          <span id="observability" />
          <Eyebrow>Substrate observability</Eyebrow>
          <h2 style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(28px, 3.5vw, 44px)", fontWeight: 500, letterSpacing: "-0.02em", color: "var(--ink)", margin: "16px 0 12px", maxWidth: 900, lineHeight: 1.1 }}>
            <em style={{ fontStyle: "italic", color: "var(--accent-2)" }}>Every</em> hook fire, every workflow, every skill &mdash; counted.
          </h2>
          <p style={{ fontSize: 16, lineHeight: 1.6, color: "var(--ink-2)", maxWidth: 900, margin: "0 0 32px" }}>
            The instrumentation-density surface — measured across every source, deduped, provenance-tracked. This section exists because a system that can&rsquo;t count its own moving parts can&rsquo;t claim to govern them.
          </p>
          <div style={{ ...gridAutoFit(220) }}>
            <StatBlock
              value={formatInt(stats.substrateObservability.skillsUniqueAcrossEstate)}
              label="Skills, unique across estate"
              detail={`${stats.substrateObservability.skillsGlobal} global · ${Object.keys(stats.substrateObservability.skillsPerRepo).length} repos contributing · ${stats.substrateObservability.skillsPluginMarketplace} plugin marketplace`}
              tone="accent"
            />
            <StatBlock
              value={formatInt(stats.substrateObservability.ghaWorkflowsTotal)}
              label="GitHub Actions workflows"
              detail={`across ${Object.keys(stats.substrateObservability.ghaWorkflowsByRepo).length} repos · nebos-governance carries ${stats.substrateObservability.ghaWorkflowsByRepo["nebos-governance"] ?? 0} alone`}
              tone="accent"
            />
            <StatBlock
              value={formatCompact(stats.substrateObservability.hookFiresTotal)}
              label="Hook fires (12-day window)"
              detail={`across ${Object.keys(stats.substrateObservability.hookFiresByLog).length} distinct hook logs · ~${Math.round(stats.substrateObservability.hookFiresTotal / 12).toLocaleString()} per day`}
              tone="accent"
            />
            <StatBlock
              value={formatInt(stats.substrateObservability.sessionMtimesCount)}
              label="Session reports auto-authored"
              detail="one per session-turn · via Stop-hook auto-doc pipeline"
              tone="accent"
            />
          </div>
        </Section>
      )}

      {/* Responsible-AI coverage — measurable */}
      {stats.responsibleAiCoverage && (
        <Section divider>
          <span id="coverage" />
          <Eyebrow>Responsible-AI coverage, measurable</Eyebrow>
          <h2 style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(28px, 3.5vw, 44px)", fontWeight: 500, letterSpacing: "-0.02em", color: "var(--ink)", margin: "16px 0 12px", maxWidth: 900, lineHeight: 1.1 }}>
            Compliance is a substrate feature. <em style={{ fontStyle: "italic", color: "var(--accent-2)" }}>Here&rsquo;s the count.</em>
          </h2>
          <p style={{ fontSize: 16, lineHeight: 1.6, color: "var(--ink-2)", maxWidth: 900, margin: "0 0 32px" }}>
            Every claim in the earlier compliance-lens section has a measurable count behind it — number of design specifications that reference each regime, number of hooks that gate consequential actions, number of migrations that adopt the row-level isolation column, number of independent AI providers wired.
          </p>
          <div style={{ ...gridAutoFit(220) }}>
            <StatBlock
              value={formatInt(stats.responsibleAiCoverage.complianceCoverage?.eu_ai_act ?? 0)}
              label="Docs referencing EU AI Act"
              detail="Annex IV, Article 14, Article 11 — architectural spec references"
            />
            <StatBlock
              value={formatInt(stats.responsibleAiCoverage.complianceCoverage?.gdpr ?? 0)}
              label="Docs referencing GDPR"
              detail="Article 17 erasure, crypto-shredding technique"
            />
            <StatBlock
              value={formatInt(stats.responsibleAiCoverage.complianceCoverage?.soc2 ?? 0)}
              label="Docs referencing SOC 2"
              detail="CC6.1 access-control, CC7 monitoring"
            />
            <StatBlock
              value={formatInt(stats.responsibleAiCoverage.complianceCoverage?.ferpa ?? 0)}
              label="Docs referencing FERPA"
              detail="aggregate-only enforcement for education records"
            />
            <StatBlock
              value={formatInt(stats.responsibleAiCoverage.approvalSurfaces?.hooks_that_gate ?? 0)}
              label="Approval gates in hook code"
              detail="hooks that fire before consequential actions — enforcement is code"
              tone="accent"
            />
            <StatBlock
              value={formatInt(stats.responsibleAiCoverage.rlsMigrations)}
              label="Row-level-security migrations"
              detail="schema changes that adopted the four-tier scope column"
              tone="accent"
            />
            <StatBlock
              value={formatInt(Object.values(stats.responsibleAiCoverage.llmProviders ?? {}).filter(v => v > 0).length)}
              label="AI providers wired"
              detail={`${Object.entries(stats.responsibleAiCoverage.llmProviders ?? {}).filter(([, v]) => v > 0).map(([k]) => k).join(" · ")} — multi-provider substrate`}
              tone="accent"
            />
            <StatBlock
              value={formatInt(stats.responsibleAiCoverage.auditTrailRefs)}
              label="Audit-trail code references"
              detail="hash-chain, append-only ledger, event-log references across every backend"
              tone="accent"
            />
          </div>
        </Section>
      )}

      {/* What we don't yet measure — honest known-unknowns */}
      <Section divider>
        <span id="unknowns" />
        <Eyebrow>What we don&rsquo;t yet measure, honestly</Eyebrow>
        <h2 style={{ fontFamily: "var(--font-serif)", fontSize: "clamp(28px, 3.5vw, 44px)", fontWeight: 500, letterSpacing: "-0.02em", color: "var(--ink)", margin: "16px 0 12px", maxWidth: 900, lineHeight: 1.1 }}>
          <em style={{ fontStyle: "italic", color: "var(--accent-2)" }}>The known gaps</em> in our own instrumentation.
        </h2>
        <p style={{ fontSize: 16, lineHeight: 1.6, color: "var(--ink-2)", maxWidth: 900, margin: "0 0 32px" }}>
          A responsible system names what it can&rsquo;t yet count. Below are the dimensions we know exist but haven&rsquo;t landed a canonical measurement for &mdash; each one is a follow-on counter, not a hole in the story.
        </p>
        <ul style={{ maxWidth: 900, margin: 0, paddingLeft: 20, fontSize: 15, lineHeight: 1.7, color: "var(--ink-2)" }}>
          <li>Workflow-definition rows in the operational database (accessible only via the projects API, not a filesystem scan)</li>
          <li>Peak within-session subagent dispatches — needs deep session-report analysis</li>
          <li>Skill and workflow <em>invocation</em> counts (which are called vs. merely declared) — needs log mining</li>
          <li>CI workflow success/failure rate per repo — needs GitHub API</li>
          <li>Session-report substantiveness distribution (which sessions did substantive work)</li>
          <li>Token spend / cost per session (not yet logged in a canonical place)</li>
          <li>Repo-touch heatmap — files touched per session, grouped by repo</li>
          <li>Full historical hour-of-day session activity (currently only rolling 12-day window)</li>
        </ul>
        <p style={{ fontSize: 12.5, color: "var(--ink-3)", margin: "24px 0 0", maxWidth: 900, lineHeight: 1.5, fontStyle: "italic" }}>
          These are follow-on counters, each with a known technique. Publishing the list is itself the instrumentation discipline the page argues for &mdash; a self-observing system knows the limits of its own observations.
        </p>
      </Section>

      {/* Every measurement */}
      <Section divider>
        <Eyebrow>Every measurement</Eyebrow>
        <p style={{ fontSize: 14, color: "var(--ink-3)", lineHeight: 1.55, maxWidth: 900, marginTop: 16, marginBottom: 32 }}>
          For readers who verify. Every number below is a count, not an estimate. The manifest is regenerated by <code style={{ fontFamily: "var(--font-mono)", fontSize: 12 }}>scripts/scan-estate.ts</code> and read at build time.
        </p>
        <div style={{ ...gridAutoFit(200) }}>
          <StatBlock value={formatInt(s.scale.reposTotal)} label="Repositories" tone="muted" />
          <StatBlock value={formatInt(s.scale.sourceFilesTotal)} label="Source files" tone="muted" />
          <StatBlock value={formatInt(s.depth.pythonCallablesTotal)} label="Python callables" detail={`${formatInt(s.depth.pythonDefs)} def · ${formatInt(s.depth.pythonAsyncDefs)} async · ${formatInt(s.depth.pythonClasses)} class`} tone="muted" />
          <StatBlock value={formatInt(s.depth.typescriptExportsTotal)} label="TypeScript exports" tone="muted" />
          <StatBlock value={formatInt(s.depth.testCasesTs)} label="TS/JS test cases" tone="muted" />
          <StatBlock value={formatInt(s.depth.testCasesPython)} label="Python test cases" tone="muted" />
          <StatBlock value={formatInt(s.depth.testFilesTotal)} label="Test files" detail={`${formatInt(s.depth.testFilesTs)} TS · ${formatInt(s.depth.testFilesPython)} Python`} tone="muted" />
          <StatBlock value={formatInt(s.depth.dbTables)} label="DB tables" tone="muted" />
          <StatBlock value={formatInt(s.depth.dbMigrationsTotal)} label="Migrations" tone="muted" />
          <StatBlock value={formatInt(s.depth.httpEndpointsBackend)} label="API routes" tone="muted" />
          <StatBlock value={formatInt(s.depth.httpEndpointsNextHandlers)} label="Frontend handlers" tone="muted" />
          <StatBlock value={formatInt(s.depth.httpEndpointsNextPages)} label="Rendered pages" tone="muted" />
          <StatBlock value={formatInt(s.rigor.architectureSpecsDraft)} label="Specs in review" tone="muted" />
          <StatBlock value={formatInt(s.rigor.architectureSpecsProvisional)} label="Provisional specs" tone="muted" />
          <StatBlock value={formatInt(s.rigor.architectureSpecsPipelineTotal)} label="Total pipeline" tone="muted" />
          <StatBlock value={formatInt(s.selfObservation.skills)} label="Installed skills" tone="muted" />
          <StatBlock value={formatInt(s.selfObservation.doctrineMemories)} label="Doctrine memories" detail={`${formatInt(s.selfObservation.feedbackMemories)} tagged as behavioral feedback`} tone="muted" />
          <StatBlock value={formatInt(s.selfObservation.sessionReports)} label="Session reports" tone="muted" />
          <StatBlock value={formatInt(s.infrastructure.containerImages)} label="Container images" tone="muted" />
          <StatBlock value={formatInt(s.infrastructure.cloudServiceConfigs)} label="Service configs" tone="muted" />
          <StatBlock value={formatInt(s.productSurface.uiComposites + s.productSurface.uiPrimitives)} label="UI modules" detail={`${s.productSurface.uiComposites} composites · ${s.productSurface.uiPrimitives} primitives`} tone="muted" />
          <StatBlock value={formatInt(s.productSurface.designTokens)} label="Design tokens" tone="muted" />
        </div>
      </Section>

      <CTABand
        headline="Every rule is code. Every decision is indexed. Every session is auditable."
        deck="This is what responsible AI looks like at institutional scale — deployed without giving up ownership, audit, or approval. Every number on this page was measured, not estimated."
        primary={{ label: "Read the full presentation", href: "/platform/presentation" }}
        secondary={{ label: "One-page argument", href: "/platform/standout" }}
      />
    </>
  );
}

// ────────────────────────────────────────────────────────────────────────────
// Local presentational primitives (compose over the existing UI kit)
// ────────────────────────────────────────────────────────────────────────────

function LanguageBar({ languages }: { languages: Record<string, number> }) {
  const entries = Object.entries(languages).sort(([, a], [, b]) => b - a);
  const total = entries.reduce((sum, [, n]) => sum + n, 0) || 1;
  const palette = ["var(--accent-2)", "var(--gold)", "var(--scene-2)", "var(--scene-3)", "var(--ink-3)", "var(--muted)"];
  return (
    <div>
      <div style={{ display: "flex", height: 12, borderRadius: 6, overflow: "hidden", background: "var(--paper-2)" }}>
        {entries.map(([name, n], i) => (
          <span key={name} title={`${name}: ${formatInt(n)} lines`} style={{ width: `${(n / total) * 100}%`, background: palette[i % palette.length], display: "block", height: "100%" }} />
        ))}
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: "6px 20px", fontSize: 12, color: "var(--ink-2)", fontFamily: "var(--font-mono)", marginTop: 12 }}>
        {entries.map(([name, n], i) => (
          <div key={name}>
            <span style={{ display: "inline-block", width: 8, height: 8, borderRadius: 2, marginRight: 8, background: palette[i % palette.length], verticalAlign: "middle" }} />
            <strong style={{ color: "var(--ink)" }}>{name}</strong> · {formatInt(n)}
          </div>
        ))}
      </div>
    </div>
  );
}

function SummaryCard({ label, body }: { label: string; body: React.ReactNode }) {
  return (
    <div style={{ borderTop: "1px solid var(--rule)", paddingTop: 18 }}>
      <p className="eyebrow" style={{ margin: "0 0 12px" }}>{label}</p>
      <p style={{ fontSize: 15, lineHeight: 1.6, color: "var(--ink-2)", margin: 0 }}>{body}</p>
    </div>
  );
}

function TrendChart({ title, values, months, current, tone = "muted" }: {
  title: string;
  values: number[];
  months: string[];
  current: number;
  tone?: "muted" | "accent";
}) {
  const max = Math.max(...values, current) || 1;
  const min = Math.min(...values, 0);
  const range = max - min || 1;
  const W = 220;
  const H = 60;
  const pad = 4;
  const step = values.length > 1 ? (W - pad * 2) / (values.length - 1) : 0;
  const points = values.map((v, i) => {
    const x = pad + i * step;
    const y = pad + (H - pad * 2) * (1 - (v - min) / range);
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(" ");
  const stroke = tone === "accent" ? "var(--accent-2)" : "var(--gold)";
  const earliest = values.find(v => v > 0) ?? 0;
  const multiplier = earliest > 0 ? (current / earliest) : 0;
  const firstMonth = months[0] ?? "";
  const lastMonth = months[months.length - 1] ?? "";

  return (
    <div style={{ borderTop: "1px solid var(--rule)", paddingTop: 16 }}>
      <p style={{
        fontFamily: "var(--font-mono)",
        fontSize: 10,
        color: "var(--ink-3)",
        letterSpacing: "0.12em",
        textTransform: "uppercase",
        fontWeight: 600,
        margin: "0 0 8px",
      }}>{title}</p>
      <p style={{
        fontFamily: "var(--font-serif)",
        fontSize: "clamp(22px, 2.4vw, 30px)",
        fontWeight: 500,
        color: "var(--ink)",
        letterSpacing: "-0.025em",
        lineHeight: 1,
        margin: "0 0 6px",
        fontVariantNumeric: "tabular-nums",
      }}>{formatCompact(current)}</p>
      {multiplier > 1.5 && (
        <p style={{ fontSize: 11, color: "var(--ink-3)", margin: "0 0 10px", fontFamily: "var(--font-mono)" }}>
          {formatCompact(earliest)} → {formatCompact(current)} · <strong style={{ color: stroke }}>{multiplier.toFixed(1)}×</strong>
        </p>
      )}
      <svg viewBox={`0 0 ${W} ${H}`} style={{ width: "100%", height: 60, display: "block", marginTop: 4 }} aria-hidden="true">
        <polyline
          points={points}
          fill="none"
          stroke={stroke}
          strokeWidth={1.5}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        {values.map((v, i) => {
          const x = pad + i * step;
          const y = pad + (H - pad * 2) * (1 - (v - min) / range);
          return <circle key={i} cx={x} cy={y} r={1.6} fill={stroke} />;
        })}
      </svg>
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: "var(--muted)", fontFamily: "var(--font-mono)", marginTop: 4, letterSpacing: "0.04em" }}>
        <span>{firstMonth}</span>
        <span>{lastMonth}</span>
      </div>
    </div>
  );
}

function ReaderPoint({ stat, label, body }: { stat: string; label: string; body: React.ReactNode }) {
  return (
    <div style={{ borderTop: "1px solid var(--rule)", paddingTop: 18 }}>
      <p style={{
        fontFamily: "var(--font-serif)",
        fontSize: "clamp(22px, 2.4vw, 30px)",
        fontWeight: 500,
        color: "var(--accent-2)",
        lineHeight: 1,
        margin: "0 0 10px",
        letterSpacing: "-0.02em",
        fontVariantNumeric: "tabular-nums",
      }}>
        {stat}
      </p>
      <p style={{
        fontFamily: "var(--font-mono)",
        fontSize: 11,
        color: "var(--ink)",
        letterSpacing: "0.06em",
        textTransform: "uppercase",
        fontWeight: 600,
        margin: "0 0 8px",
      }}>
        {label}
      </p>
      <p style={{ fontSize: 14, lineHeight: 1.55, color: "var(--ink-2)", margin: 0 }}>
        {body}
      </p>
    </div>
  );
}

function SubstrateCard({ letter, title, headline, body }: { letter: string; title: string; headline: string; body: React.ReactNode }) {
  return (
    <div style={{ borderTop: "1px solid var(--rule)", paddingTop: 20 }}>
      <p style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--muted)", letterSpacing: "0.14em", textTransform: "uppercase", margin: 0, marginBottom: 12 }}>
        {letter} · {title}
      </p>
      <h3 style={{ fontFamily: "var(--font-serif)", fontSize: 20, fontWeight: 500, color: "var(--ink)", letterSpacing: "-0.015em", margin: "0 0 12px", lineHeight: 1.25 }}>
        {headline}
      </h3>
      <p style={{ fontSize: 14, lineHeight: 1.55, color: "var(--ink-2)", margin: 0 }}>{body}</p>
    </div>
  );
}
